### ISSUE TITLE
Zero landing page support

### ISSUE THREAD

**Issue by dtoki** [commitdev/zero#222]
As a _zero_ user, I'd like to have a landing page (possibly using Gatsby) on my `root` host domain with a ci/cd pipeline so that I have a smoother pathway to going live on day n.

**Planned work:**
- [x] [New Zero module](https://github.com/commitdev/zero-deployable-landing-page/tree/dev)
  - [x] fix `jest` test errors.
  - [x] finish up documentation on the repo root.
- [x] Route 53 DNS record config
- [x] CI/CD
  - [x] templated out correctly on new zero module
  - [x] pipline started at the end of `zero apply`
  - [x] unit tests working
  - [x] test e2e
- [x] CloudFront
- [x] Sync with S3
  - [x] create bucket with the `zero apply` step
  - [x] ci/cd can sync with the created bucket
